name: "SonarQube Scan"

on:
  push:
    branches: 
      - main
    tags:
      - "sonar-**"
      - "v**"
    paths:
      - "**"
      - "!.github/**"
      - "!deployment/**"
  pull_request:
    branches:
      - "main"
      - "feat/**"
    paths:
      - "**"
      - "!.github/**"
      - "!deployment/**"

jobs:
  sonar_scan:
    uses: smallcase/sc-infra-configs/.github/workflows/sonarqube_scan.yaml@master
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT  || 'staging' }}
      RUNNER_NAME: arc-runner-set-dind
      APPLICATION_NAME: "gw-mob-ios-swift-package"
      BRANCH_NAME: "${{ github.ref_name }}"
      SONAR_SCAN: true
    secrets: inherit
